In [ ]:
#create any 3 dimensional array and practice indexing

In [ ]:
import numpy as np


array_3d = np.array([[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]],
                     [[9, 10], [11, 12]]])

print(array_3d[0, 1, 1])
print(array_3d[:, :, 0])
print(array_3d[2, :, :])

4
[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[ 9 10]
 [11 12]]


In [ ]:
#create array of suqares of keys of below dictionary
#d = {1:2,2:3,3:4,4:5}

In [ ]:
d = {1: 2, 2: 3, 3: 4, 4: 5}

squares = np.array([k**2 for k in d.keys()])
print(squares)


[ 1  4  9 16]


In [ ]:
# multiply any 2 dim array to identity matrix (2*2) and comment on result


In [2]:

import numpy as np


A = np.array([[3, 5],
              [7, 9]])

I = np.eye(2)

result = np.dot(A, I)

print(result)
# Multiplying by the identity matrix returns the same matrix.
# The result is unchanged.
# This happens because matrix multiplication in NumPy often returns floating-point values
#Notice that the result is returned as a float array, even though the original matrix had integers


[[3. 5.]
 [7. 9.]]
